// AUTO-GENERATED by `npm run font -- update-register` from src-font/fonts.json.
// Do not edit by hand - changes here will be overwritten on the next run.

export const SUPPORTED_FACES: ReadonlyArray<{ fontName: string; style: string; size: number }> = [
  { fontName: 'Standard', style: 'Regular', size: 12 },
  { fontName: 'Standard', style: 'Bold', size: 12 },
  { fontName: 'Standard', style: 'Italic', size: 12 },
  { fontName: 'Standard', style: 'Regular', size: 24 },
]
