const CATEGORIES_URL = '/win-55-ui/emoji/emoji-categories.json'

export interface ShortcodeEntry {
  emoji: string
  code: string
  category: string
  tags: string[]
  shortcodes: string[]
}

export interface ShortcodeMatch {
  emoji: string
  code: string
  shortcode: string
}

let indexPromise: Promise<ShortcodeEntry[]> | null = null

/**
 * Loads `emoji-categories.json` (generated by `npm run emoji -- classify`)
 * at runtime, caching the result so it's only fetched once.
 */
export async function loadShortcodeIndex(): Promise<ShortcodeEntry[]> {
  if (!indexPromise) {
    indexPromise = fetch(CATEGORIES_URL).then((response) => {
      if (!response.ok) {
        throw new Error(
          `Could not load emoji categories from ${CATEGORIES_URL}: ${response.status} ${response.statusText}`,
        )
      }

      return response.json() as Promise<ShortcodeEntry[]>
    })
  }

  return indexPromise
}

/** Prefix-matches a partial shortcode (e.g. "piz") against known shortcode names. */
export async function searchShortcodes(prefix: string, limit = 8): Promise<ShortcodeMatch[]> {
  const query = prefix.trim().toLowerCase()

  if (!query) {
    return []
  }

  const entries = await loadShortcodeIndex()
  const matches: ShortcodeMatch[] = []

  for (const entry of entries) {
    const matchedShortcode = entry.shortcodes.find((name) => name.toLowerCase().startsWith(query))

    if (!matchedShortcode) {
      continue
    }

    matches.push({ emoji: entry.emoji, code: entry.code, shortcode: matchedShortcode })

    if (matches.length >= limit) {
      break
    }
  }

  return matches
}

/** Exact (not prefix) match, used to resolve a fully-typed `:name:`. */
export async function resolveShortcode(
  name: string,
): Promise<{ emoji: string; code: string } | undefined> {
  const query = name.trim().toLowerCase()

  if (!query) {
    return undefined
  }

  const entries = await loadShortcodeIndex()
  const entry = entries.find((candidate) =>
    candidate.shortcodes.some((shortcode) => shortcode.toLowerCase() === query))

  return entry ? { emoji: entry.emoji, code: entry.code } : undefined
}

/** Clears the cached index. Useful if a host app swaps the categories URL at runtime. */
export function resetShortcodeIndexCache(): void {
  indexPromise = null
}
