<script setup lang="ts">
import { computed } from 'vue'
import { typographyStyles, type TypographySettings } from '../helpers/typography'

interface Props extends TypographySettings {
  element?: string
  /** Box generated by the default span wrapper; ignored when `element` is set. */
  display?: 'inline' | 'contents'
}

const props = withDefaults(defineProps<Props>(), {
  element: undefined,
  display: 'inline',
})

const tag = computed(() => props.element ?? 'span')

const styles = computed(() => {
  const s = typographyStyles(props)
  if (!props.element) {
    s.display = props.display
  }
  return s
})
</script>

<template>
  <component :is="tag" :style="styles">
    <slot />
  </component>
</template>
