import { relative } from 'node:path'
import type { FontsManifest } from './fontsManifest.js'
import { tofuTtfFilename, tofuFamilyName } from './fontsManifest.js'
import { publicUrlPrefix, projectRoot, fontsManifestPath } from './paths.js'

// Derived rather than hardcoded a second time; forced to forward slashes since this is prose, not a real path.
const fontsJsonRelativePath = relative(projectRoot, fontsManifestPath).replace(/\\/g, '/')

const GENERATED_BANNER_TS = [
  `// AUTO-GENERATED by \`npm run font -- update-register\` from ${fontsJsonRelativePath}.`,
  '// Do not edit by hand - changes here will be overwritten on the next run.',
].join('\n')

const GENERATED_BANNER_CSS = [
  `/* AUTO-GENERATED by \`npm run font -- update-register\` from ${fontsJsonRelativePath}. */`,
  '/* Do not edit by hand - changes here will be overwritten on the next run. */',
].join('\n')

/**
 * `SUPPORTED_FACES` used to be a hand-maintained array in typography.ts, kept in sync with
 * index.css's @font-face blocks by convention (and, later, by a text-splice CLI command). Both are
 * now fully derived from fonts.json instead - this produces the .ts module typography.ts imports.
 */
export function buildSupportedFacesModule(manifest: FontsManifest): string {
  const entries = manifest.faces.map((face) => `  { fontName: '${face.fontName}', style: '${face.style}', size: ${face.size} },`)

  return [
    GENERATED_BANNER_TS,
    '',
    'export const SUPPORTED_FACES: ReadonlyArray<{ fontName: string; style: string; size: number }> = [',
    ...entries,
    ']',
    '',
  ].join('\n')
}

/**
 * The @font-face counterpart to `buildSupportedFacesModule` - same source of truth (fonts.json),
 * imported once from index.css via `@import './generated-fonts.css';`. `font-family` is
 * reconstructed as `{fontName}-{style}-{size}` (not read from `face.ttf`) because that's the exact
 * string typography.ts's `typographyStyles()` builds at runtime to select this face - the two must
 * stay byte-identical. `face.ttf` only decides where the file physically is.
 *
 * Each face also gets a second block for its TofuMaker companion (see tofu.ts) - every codepoint
 * we don't have real ink for renders as that face's own pixel-style '?' instead of falling
 * through past it to a system font, as long as typography.ts appends it to the font-family stack.
 */
export function buildFontFaceCss(manifest: FontsManifest): string {
  const blocks = manifest.faces.flatMap((face) => [
    [
      '@font-face {',
      `  font-family: "${face.fontName}-${face.style}-${face.size}";`,
      `  src: url("${publicUrlPrefix}/font/${face.ttf}")`,
      '}',
    ].join('\n'),
    [
      '@font-face {',
      `  font-family: "${tofuFamilyName(face)}";`,
      `  src: url("${publicUrlPrefix}/font/${tofuTtfFilename(face)}")`,
      '}',
    ].join('\n'),
  ])

  return `${GENERATED_BANNER_CSS}\n\n${blocks.join('\n\n')}\n`
}
